@startuml
'class diagram

class client {
    - BUFFER_SIZE
    - MAX_VLAKIEN
    -ThreadInfo
    + main()
    + logger(char *log, bool write) : void
    + parse_url(const char *url, char *hostname, char *path, bool *is_https) : int
    + directoryExists(const char *path) : bool
    + downFolderPath(char* newPath, bool write) : char*
    + extract_filename(const char* url) : const char*
    + create_ssl_context() : SSL_CTX*
    + parseFtpUrl(const char *fullUrl, char *ftpHost, char *ftpPath) : void
    + threadFunc(void *arg) : void
}

@enduml
